<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{406a3466-7798-477d-9e53-8c15d5997cde}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	mainTest : fbLED_Toggle;
	btn : bool;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
mainTest(bToggleBtn := btn);
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>